require: rubocop-rspec

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'beryl.gemspec'

Layout/ExtraSpacing:
  Exclude:
    - 'beryl.gemspec'

Layout/SpaceAroundOperators:
  Exclude:
    - 'beryl.gemspec'

RSpec/SubjectStub:
  Exclude:
    # this is an abstract class anyway
    - 'spec/beryl/syntax/node_spec.rb'
