require: rubocop-rspec

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'beryl.gemspec'

Layout/ExtraSpacing:
  Exclude:
    - 'beryl.gemspec'

Layout/SpaceAroundOperators:
  Exclude:
    - 'beryl.gemspec'
